- name: A become=yes block
  become: yes
  block:
    - name: Create pool onedata
      shell: sudo ceph osd pool create onedata 256
    - name: Fetch ceph.conf
      fetch:
        src: /etc/ceph/ceph.conf
        dest: /tmp/files/
        flat: yes
    - name: Fetch ceph.client.admin.keyring
      fetch:
        src: /etc/ceph/ceph.client.admin.keyring
        dest: /tmp/files/
        flat: yes
      
